name: Solsta Promote Action
description: Promote a release
inputs:
  solsta_client_id:
    description: Client ID to authenticate usage of Solid State Networks console tools
    required: true
    default: ""
  solsta_client_secret:
    description: Secret Key to authenticate usage of Solid State Networks console tools
    required: true
    default: ""
  console_version:
    description: Version of Solsta Console Tools to use
    required: true
    default: "6.1.1.12"
  scripts_version:
    description: Version of Solsta Deploy Scripts to use
    required: true
    default: "3.7.16"
  source_product:
    description: Source product to promote from (case-sensitive)
    required: true
  source_environment:
    description: Source environment to promote from (case-sensitive)
    required: true
  source_repository:
    description: Source repository to promote from (case-sensitive)
    required: true
  target_product:
    description: Target product to promote to (case-sensitive)
    required: true
  target_environment:
    description: Target environment to promote to(case-sensitive)
    required: true
  target_repository:
    description: Target repository to promote to (case-sensitive)
    required: true

outputs:
  result:
    description: The state of the action, if processes completed successfully

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.solsta_client_id }}
    - ${{ inputs.solsta_client_secret }}
    - ${{ inputs.console_version }}
    - ${{ inputs.scripts_version }}
    - ${{ inputs.target_product }}
    - ${{ inputs.target_environment }}
    - ${{ inputs.target_repository }}
    - ${{ inputs.source_product }}
    - ${{ inputs.source_environment }}
    - ${{ inputs.source_repository }}
branding:
  icon: "download-cloud"
  color: "yellow"
